# Use Python 3.5 for our tooling
language: python
python:
  - "3.5"
sudo: required
services:
  - docker
matrix:
  # Don’t wait for jobs that are allowed to fail
  fast_finish: true

before_install:
  - docker pull amarschke/flycheck-ci-docker

script:
  - make docker

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/efdc5fd9433efa7c6b80
    on_success: change
    on_failure: always
    on_start: never

