# Use Python 3.5 for our tooling
language: python
python:
  - "3.5"
sudo: required
services:
  - docker
matrix:
  # Don’t wait for jobs that are allowed to fail
  fast_finish: true

before_install:
  - docker pull amarschke/flycheck-ci-docker

script:
  - docker run --rm \
               --volume $TRAVIS_BUILD_DIR:/home/flycheck-tester/flycheck \
               --name "FlycheckTesting" \
               --workdir /home/flycheck-tester/flycheck \
               --entrypoint "/bin/bash" \
               -it amarschke/flycheck-ci-docker \
               /bin/bash -c ". ~/.bash_profile && make init check compile specs unit integ"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/efdc5fd9433efa7c6b80
    on_success: change
    on_failure: always
    on_start: never

